---
abstract: 'backups imap mail'
author:
  - 'Alex Muntada <alexm@cpan.org>'
build_requires:
  Path::Class::Dir: 0
  Test::MockModule: 0
  Test::Moose: 0
  Test::More: 0
  Test::TestCoverage: 0.11
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200006, CPAN::Meta::Converter version 2.110420'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-backimap
requires:
  Data::Dump: 0
  Encode: 0
  Encode::IMAPUTF7: 0
  English: 0
  File::HomeDir: 0
  Git::Wrapper: 0.014
  IO::Prompt: 0
  IO::Scalar: 0
  IO::Socket::SSL: 0
  JSON::Any: 0
  MIME::Parser: 0
  Mail::IMAPClient: 0
  Moose: 0
  Moose::Util::TypeConstraints: 0
  MooseX::Getopt: 0
  MooseX::Storage: 0
  MooseX::Types::Path::Class: 0
  Path::Class: 0
  Storable: 0
  Term::ProgressBar: 0
  Try::Tiny: 0
  URI: 0
  URI::Escape: 0
  URI::imap: 0
  URI::imaps: 0
  version: 0
resources:
  repository: http://github.com/alexm/App-backimap.git
version: 0.00_13
