---
abstract: 'backups imap mail'
author:
  - 'Alex Muntada <alexm@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.110580'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-backimap
requires:
  Carp: 0
  English: 0
  File::HomeDir: 0
  File::Path: 0
  File::Spec::Functions: 0
  File::chdir: 0
  Getopt::Long: 0
  Git::Wrapper: 0
  IO::Prompt: 0
  IO::Socket::SSL: 0
  Mail::IMAPClient: 0
  Moose: 0
  Moose::Util::TypeConstraints: 0
  MooseX::Storage: 0
  Path::Class::Dir: 0
  Path::Class::File: 0
  Pod::Usage: 0
  URI: 0
  perl: 5.010
resources:
  repository: git://github.com/alexm/App-backimap.git
version: 0.00_06
